In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv", index_col = 'RowNumber')
dataset.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [4]:
X_columns = dataset.columns.tolist()[2:12]
Y_columns = dataset.columns.tolist()[-1:]
print(X_columns)
print(Y_columns)

['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
['Exited']


In [5]:
X = dataset[X_columns].values
Y = dataset[Y_columns].values

In [6]:
from sklearn.preprocessing import LabelEncoder
X_column_transformer = LabelEncoder()
X[:, 1] = X_column_transformer.fit_transform(X[:, 1])

In [7]:
X[:, 2] = X_column_transformer.fit_transform(X[:, 2])

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Assuming you want to apply StandardScaler in your pipeline
pipeline = Pipeline([('scaler', StandardScaler())])

X = pipeline.fit_transform(X)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [11]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input

# Initialize the classifier
classifier = Sequential()

# Add input layer and hidden layer
classifier.add(Dense(units=6, activation='relu', input_dim=X_train.shape[1]))
classifier.add(Dropout(rate=0.1))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [13]:
#Add output layer
classifier.add(Dense(1, activation = 'sigmoid'))

In [14]:
#Let us take a look at our network
classifier.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 6)                   │              66 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 6)                   │              42 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               7 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 115 (460.00 B)

 Trainable params: 115 (460.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
#Optimize the weights
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
#Fitting the Neural Network
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 2s - 9ms/step - accuracy: 0.7443 - loss: 0.5565 - val_accuracy: 0.7950 - val_loss: 0.4785
Epoch 2/200
225/225 - 0s - 2ms/step - accuracy: 0.7904 - loss: 0.4856 - val_accuracy: 0.7950 - val_loss: 0.4487
Epoch 3/200
225/225 - 1s - 3ms/step - accuracy: 0.7917 - loss: 0.4721 - val_accuracy: 0.7962 - val_loss: 0.4375
Epoch 4/200
225/225 - 1s - 3ms/step - accuracy: 0.7928 - loss: 0.4596 - val_accuracy: 0.7962 - val_loss: 0.4308
Epoch 5/200
225/225 - 0s - 2ms/step - accuracy: 0.7958 - loss: 0.4573 - val_accuracy: 0.7975 - val_loss: 0.4274
Epoch 6/200
225/225 - 1s - 3ms/step - accuracy: 0.7985 - loss: 0.4487 - val_accuracy: 0.7975 - val_loss: 0.4256
Epoch 7/200
225/225 - 1s - 3ms/step - accuracy: 0.7976 - loss: 0.4482 - val_accuracy: 0.8012 - val_loss: 0.4235
Epoch 8/200
225/225 - 0s - 2ms/step - accuracy: 0.8001 - loss: 0.4396 - val_accuracy: 0.8000 - val_loss: 0.4221
Epoch 9/200
225/225 - 1s - 3ms/step - accuracy: 0.8037 - loss: 0.4406 - val_accuracy: 0.8025 - val_loss:

In [17]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.25313982]
 [0.37552872]
 [0.22900529]
 [0.10760587]
 [0.08244287]]


In [18]:
#Let us use confusion matrix with cutoff value as 0.5
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [19]:
#Making the Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1544   51]
 [ 208  197]]


In [20]:
#Accuracy of our NN
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

87.05 % of data was classified correctly
